### PR TITLE
Plotters to visualize training errors

### PR DESCRIPTION
**Pull request by lakehanne**
This commit [e48d70a](https://github.com/Element-Research/rnn/commit/e48d70a000502b79daaa92ca27910340b4c4d1ab) adds loggers and plots from the optim class to visualize errors during training for the examples. You can ignore the [8c74cd4](https://github.com/Element-Research/rnn/commit/8c74cd47eee29db72236e83a70484d8eb82fb702), [d1024e1](https://github.com/Element-Research/rnn/commit/d1024e19e198b99af678d1f6f7fd0da895f03c28) and [    5a7238e](https://github.com/Element-Research/rnn/commit/5a7238ef59e641daad0efa1afdfd72312e321dba) commits.

Cheers!

### CODE REVIEW

**Comment by ywelement** [comment]
Thanks, @lakehanne. There were some issues merging your PR. I've manually add your changes to include the plot option.

**Comment by lakehanne** [comment]
Okay cool!

**Comment by ywelement** [comment]
btw, @lakehanne, for the examples, I mostly merged your changes on recurrent-time-series.lua since it comes with a nice 'plot' option which gives the user a choice whether the log will be generated or not. If you would like me to merge loggers and plotters in other examples in your PR, could you update the scripts to add the 'plot' option as well such that they don't have to generate the logs by default. Appreciate it.

**Comment by lakehanne** [comment]
I'm kinda busy right now. I could see myself doing that in the next few weeks.

Sincerely,
Lekan

**Comment by ywelement** [comment]
Sounds good. There's no rush. Thanks for taking care of it, @lakehanne.

**Comment by nicholas-leonard** [comment]
Closing this for now.

**Pull request closed without merging**
