### PR TITLE
Lstm

### PR DESCRIPTION
**Pull request by lobachevzky**
This is a minor change, but the original paper specifies LSTMs for the core network. I replaced the Linear layer on line 123 with a FastLSTM layer, and while the model trains more slowly, it appears to achieve better accuracies.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@lobachevzky could you make the FastLSTM optional . So adding a `cmdline:option('--lstm'....)` option would do the trick.

**Comment by lobachevzky** [comment]
I think this should do it. Was this what you had in mind?

**Comment by lobachevzky** [comment]
Nicholas,
I forgot to answer your second question. Specifically I was referring to DeepMind’s "Recurrent Models of Visual Attention.”

On page 6, they write:
‘''
Core network: For the classification experiments that follow the core f_h was a network of rectifier units defined as h_t = f_h(h_t−1) = Rect(Linear(h_t−1) + Linear(g_t)). The experiment done on a dynamic environment used a core of LSTM units [10].
‘’'

I’ve also played with the code and in general, LSTMs seem to increase accuracy.

Ethan

**Comment by nicholas-leonard** [comment]
@lobachevzky Ok. So I think they use LSTM only for the non-MNIST experiment.

**Comment by lobachevzky** [comment]
I see. I didn’t realize that’s what they meant by “dynamic environment.”

**Comment by nicholas-leonard** [comment]
@lobachevzky In any case, your PR is a nice addition if it indeed does provide for better performance :)

**Comment by lobachevzky** [comment]
Glad I could help!

**Pull request merged**
