### PR TITLE
Based on @viorik observations in #252

### PR DESCRIPTION
**Pull request by lakehanne**
Separates biases from normalization, initializes beta's to zero and gammas to 0.1.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@lakehanne Your PR was broken. I fixed it here : https://github.com/Element-Research/rnn/commit/fb6aaea2efb6b9ddc9449779d72318460fcc613d

**Comment by lakehanne** [comment]
Cheers!

**Comment by lakehanne** [comment]
Is `noBias` a Torch method? 

I had errors when implementing your fix:

```lua
...NT/ogunmolu/torch/install/share/lua/5.1/rnn/FastLSTM.lua:116: attempt to call method 'noBias' (a nil value)
stack traceback:
	...NT/ogunmolu/torch/install/share/lua/5.1/rnn/FastLSTM.lua:116: in function 'buildModel'
	...al/ANT/ogunmolu/torch/install/share/lua/5.1/rnn/LSTM.lua:20: in function '__init'
	...NT/ogunmolu/torch/install/share/lua/5.1/rnn/FastLSTM.lua:14: in function '__init'
	.../ANT/ogunmolu/torch/install/share/lua/5.1/torch/init.lua:91: in function <.../ANT/ogunmolu/torch/install/share/lua/5.1/torch/init.lua:87>
```

**Comment by JoostvDoorn** [comment]
You should probably update the nn package.

**Comment by nicholas-leonard** [comment]
@lakehanne Yup. https://github.com/torch/nn/blob/master/Linear.lua#L15

**Pull request closed without merging**
