### PR TITLE
GRU implementation.

### PR DESCRIPTION
**Pull request by jnhwkim**
For #63, Benchmark on `PennTreeBank` dataset using `recurrent-language-model.lua`. It slightly outperfomed `nn.FastLSTM`.

                Memory   examples/s
    FastLSTM      176M        16.5K 
    GRU            92M        15.8K

__Memory__ is measured by the size of `dp.Experiment` save file. __examples/s__ is measured by the training speed at 1 epoch, so, it may have a disk IO bias.

Few notes: i) sorry for poor naming of variables. ii) I'm not sure about usage of `nn.LinearNoBias` for some units of `nn.FastLSTM`, however, I followed the presumed convention of `nn.FastLSTM`.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@jnhwkim Wow that was fast! Could you add unit test and doc? Doesn't need to be much. For the unit test, just some tests to make sure the updateOutput,updateGradOutput and accGradParameters do what they are supposed to do. For doc, reference to original paper and small explanation of theory.

Thank you so much for this PR. GRU is awesome, was just too occupied to implement it myself.

**Comment by jnhwkim** [comment]
Separately unit test on GRU works fine, however refer #69 and the doc is updated with a benchmark.

**Comment by jnhwkim** [comment]
For note ii), I found previous commit ec6d9df8dbd3bb602a7f02379d42087222bf095b. It confirms what I commited is right.

**Comment by nicholas-leonard** [comment]
@jnhwkim This is the best Pull Request I have had the opportunity to merge. Keep em coming. Thanks.

**Comment by jnhwkim** [comment]
@nicholas-leonard You're welcome!

**Pull request merged**
