### PR TITLE
MaskZero can pad anywhere in sequence

### PR DESCRIPTION
**Pull request by nicholas-leonard**
Updated doc and included a unit test (not change to core code as this was always possible, just never unit tested).

### CODE REVIEW

**Comment by Beanocean** [comment]
Hello, @nicholas-leonard .
When try to apply ZeroMask to a certain timestep, I think we should set the gradOutput as *1* but not *0* according to the chain rule of partial derivative, because we need to multiply the gradient of each layer. If we set the derivative of zero-padded elements as *0*, the whole partial derivative of this sequence will become *0*. In the implementation of `MaskZero.lua:`:
```lua
function MaskZero:updateGradInput(input, gradOutput)
   -- zero gradOutputs before backpropagating through decorated module
   self.gradOutput = self:recursiveMask(self.gradOutput, gradOutput, self.zeroMask)
   
   self.gradInput = self.module:updateGradInput(input, self.gradOutput)
   return self.gradInput
end
```
I think the function `self:recursiveMask()` set the corresponding rows of `self.gradOutput` as *0*.

**Comment by nicholas-leonard** [comment]
@Beanocean I want the whole partial derivative to become zero if the input is masked. Otherwise the gradients w.r.t. parameters will accumulate garbage/invalid derivatives for the masked inputs.

**Comment by maydaygmail** [comment]
@nicholas-leonard @Beanocean I have a puzzle on
`self.gradInput = self.module:updateGradInput(input, self.gradOutput)` in `function MaskZero:updateGradInput(input, gradOutput)`

lstm = FastLSTM():maskZero(1)
lstm:forward()
however, FastLSTM has no updateGradInput, how it works?

**Comment by nicholas-leonard** [comment]
@maydaygmail FastLSTM inherits that method from LSTM.

**Comment by maydaygmail** [comment]
@nicholas-leonard I am sorry for unclear description. That is a typo, I want to say 'updateOutput' not 'updateGradInput'. lstm:forward() first will call 'updateOutput' inherits from LSTM, and in the method [https://github.com/Element-Research/rnn/blob/master/LSTM.lua#L162](url) line 162 `output, cell = unpack(recurrentModule:updateOutput{input, prevOutput, prevCell})` , will call 'updateOutput' method in MaskZero, and in the method [https://github.com/Element-Research/rnn/blob/master/MaskZero.lua#L75](url) line 75 `local output = self.module:updateOutput(input)` would also call the method in LSTM? I think the last call `updateOutput` in MaskZero would call FastLSTM, but FastLSTM has no the method.

**Comment by nicholas-leonard** [comment]
> `local output = self.module:updateOutput(input)` would also call the method in LSTM?
In that line, the `self.module` is the `FastLSTM.recurrentModule`. So it isn't a dead loop. The MaskZero module decorates the FastLSTM.recurrentModule, not the FastLSTM itself.

**Comment by maydaygmail** [comment]
I see~~ Thank you @nicholas-leonard

**Pull request merged**
