### PR TITLE
Add a reference for TrimZero

### PR DESCRIPTION
**Pull request by jnhwkim**
It's a published two-page technical paper.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@jnhwkim Nice!

**Comment by jnhwkim** [comment]
@nicholas-leonard thanks!

**Comment by jnhwkim** [comment]
I did little more experiment on CUDA. Efficiency of `TrimZero` is degradation for CUDA computing, however, it is mainly affected by `batch size`, `rnn size` and `number of zeros in inputs`. Empirically, natural language sentences (around mean length 7~8, max length 26) with `batch size` = 200 and `rnn size` = 2400 (skip-thought vectors) gain decent computational advantage (+37.5%) for CUDA computing.

**Comment by nicholas-leonard** [comment]
@jnhwkim That is good to know.

**Pull request merged**
