### PR TITLE
Add opencl

### PR DESCRIPTION
**Pull request by hughperkins**
Hi Nicholas,

I had to make the changes below, to get neuralconvo to run on opencl, for fixing https://github.com/hughperkins/distro-cl/issues/8#issuecomment-240993797

Hugh

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@hughperkins Thanks. Sorry for delay. Just finished moving back to Canada :)

**Comment by hughperkins** [comment]
Thanks! :-)

**Comment by hughperkins** [comment]
(For info, rocks-cl now no longer redirects rnn installation to my rnn fork, and installation of rnn on distro-cl will now come from the main Element-Research/rnn repo again now https://github.com/hughperkins/rocks-cl/commit/9055c7f1d3a6fa9dc79c245ae4789991a7a6ba46 )

**Comment by nicholas-leonard** [comment]
Cool thanks!

**Pull request merged**
