### PR TITLE
Multivariate time series example

### PR DESCRIPTION
**Pull request by rracinskij**
modification of the original recurrent-time-series.lua example based on discussion in issue #113

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@rracinskij This script is not a time-series example anymore. Nor is it really learning a sequence as the input for each time step is columns 1 and 2 and the target is 3. Knowledge of the previous time-steps does little to help in solving this task.

**Comment by zencoding** [comment]
@rracinskij @nicholas-leonard my original problem statement for time series was a simple alternating time series with odd sequence having target as addition of column 1 and column 2 and even sequence having target as multiplication of column 1 and column 2.  I think this would classify as a time series problem where knowledge of previous time-steps required to determine the current output

**Comment by nicholas-leonard** [comment]
@zencoding I am also new to time series. Based on the [Wikipedia Time Series page](https://en.wikipedia.org/wiki/Time_series), your example doesn't fit the bill. They seem to say that for time series, the data is a sequence. So in your case, the only way you could say that it is would be to have your sequence be something like : a, b, a+b, c, d, c+d, etc. If the first 5 elements are fed in as inputs, the last 5 are their commensurate targets. That would be a valid time-series.

**Comment by rracinskij** [comment]
@nicholas-leonard While simplifying the initial example I threw the baby out with the bathwater, as each value can be predicted without knowing the past ones. So you're right, it doesn't make sense, the input should be modified.

**Comment by nicholas-leonard** [comment]
> I threw the baby out with the bathwater
lulz

**Comment by rracinskij** [comment]
Just added some random events to the initial sequence that affect current and future values (set the target with p=0.2 to 0 and the next target to -0.5), the model is learning:
sequence = torch.Tensor(opt.dataSize,3):fill(0)
i=0.1
for j = 2,opt.dataSize do
sequence[j][1]= i --fill column 1
sequence[j][2] = i + 0.01 --fill column 2
sequence[j][3] = sequence[j][1] + sequence[j][2]--fill column 3
local randomEvent=torch.rand(1)
if randomEvent[1]>0.8 and sequence[j-1][3]>0 then sequence[j][3]=0 end --add random events that affect current and future outputs
if sequence[j-1][3]==0 then sequence[j][3] = -0.5 end
i=i+0.01
if sequence[j][3] >0.99 then i=0 end
end
print('Sequence:'); print(sequence)

**Comment by nicholas-leonard** [comment]
@rracinskij One thing I continue to find odd and that I should have mentioned is the encapsulation of an LSTM as a recurrent layer to the Recurrent module. This is non-standard use of RNNs. I am thinking you should use either or. Don't get me wrong, our package supports this kind of hacky magic. But it is non-standard which means you it will raise some eyebrows unless you can prove through publishing results in a paper that your new kind of model works better. I wouldn't be surprised that it works better than just an LSTM or an RNN.

In any case, for now I would replace Recurrent(LSTM) with just LSTM.

**Comment by nicholas-leonard** [comment]
@rracinskij And I think your example is still not a time-series example per-say as the target at time t is not the input for time t+1.

**Comment by rracinskij** [comment]
@nicholas-leonard in the updated example the target in column 3 in t=0 is the input for t=1. But yes, it's still a bit odd, as target in column 3 depends on values in columns 1 and 2 at the same time point. It was just a modification of original sequence while dealing with issue #113. 

Could you please provide the correct model for LSTM?

**Comment by nicholas-leonard** [comment]
correct models in #113.

**Pull request closed without merging**
